version: '3.8'
services:
    client:
        build:
            context: client
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - 5173:5173
    comments:
        build:
            context: comments
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./comments:/app
            - /app/node_modules
        ports:
            - 4001:4001
    posts:
        build:
            context: posts
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./posts:/app
            - /app/node_modules
        ports:
            - 4000:4000
    events:
        build:
            context: event-bus
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./event-bus:/app
            - /app/node_modules
        ports:
            - 4005:4005
