version: '3.8'
services:
    client:
        build:
            context: client
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - 5173:5173
    posts:
        build:
            context: posts
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./posts:/app
            - /app/node_modules
        ports:
            - 4000:4000
    comments:
        build:
            context: comments
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./comments:/app
            - /app/node_modules
        ports:
            - 4001:4001
    query:
        build:
            context: query
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./query:/app
            - /app/node_modules
        ports:
            - 4002:4002
        depends_on:
            - events
    moderation:
        build:
            context: moderation
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./moderation:/app
            - /app/node_modules
        ports:
            - 4003:4003
    events:
        build:
            context: event-bus
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./event-bus:/app
            - /app/node_modules
        ports:
            - 4005:4005
